export const receipeActionTypes = {
  START_FETCHING_RECEIPES: "START_FETCHING_RECEIPES",
  SUCCESS_FETCHING_RECEIPES: "SUCCESS_FETCHING_RECEIPES",
  FAIL_FETCHING_RECEIPES: "FAIL_FETCHING_RECEIPES",
};
